[project]
name = "adaptive-cards-python"
version = "0.1.0"
description = "Fully typed & validated Adaptive Card implementation in pydantic."
readme = "README.md"
authors = [{ name = "Emir Karamehmetoglu", email = "emirk@axis.com" }]
requires-python = ">=3.12"
dependencies = [
    "pydantic-extra-types>=2.10.4",
    "pydantic>=2.11.4",
    "datamodel-code-generator[http]",
    "orjson>=3.10.18",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest>=8.3.5", "ruff>=0.11.8"]
