[project]
name = "adaptive-cards-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Emir Karamehmetoglu", email = "emirk@axis.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic-extra-types>=2.10.4",
    "pydantic>=2.11.4",
    "datamodel-code-generator[http]",
    "ruff>=0.11.8",
    "orjson>=3.10.18",
    "pytest>=8.3.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
